// svelte-app/src/views/LoadView.svelte
<div class="max-w-4xl mx-auto">
  <h1 class="text-5xl font-bold mt-8 mb-4 text-center text-gray-800">
    Добро пожаловать в магазин
  </h1>

  <div class="prose prose-lg mx-auto">
    <p class="mb-4">
      Здесь вы найдёте тысячи товаров по самым низким ценам. Мы работаем с
      ведущими поставщиками и гарантируем качество.
    </p>
    <p class="mb-4">
      Наша платформа использует современные технологии для быстрой и плавной
      работы. Оцените скорость загрузки и удобство интерфейса.
    </p>
    <p class="mb-6">
      Для перехода к каталогу нажмите кнопку ниже или воспользуйтесь меню.
    </p>
  </div>

  <div class="flex justify-center">
    <button
      class="bg-blue-600 text-white px-6 py-3 rounded-lg shadow hover:bg-blue-700 transition"
    >
      Начать покупки
    </button>
  </div>
</div>

// vue-app/src/views/LoadView.vue
<template>
  <div class="max-w-4xl mx-auto">
    <h1 class="text-5xl font-bold mt-8 mb-4 text-center text-gray-800">
      Добро пожаловать в магазин
    </h1>

    <div class="prose prose-lg mx-auto">
      <p class="mb-4">
        Здесь вы найдёте тысячи товаров по самым низким ценам. Мы работаем с
        ведущими поставщиками и гарантируем качество.
      </p>
      <p class="mb-4">
        Наша платформа использует современные технологии для быстрой и плавной
        работы. Оцените скорость загрузки и удобство интерфейса.
      </p>
      <p class="mb-6">
        Для перехода к каталогу нажмите кнопку ниже или воспользуйтесь меню.
      </p>
    </div>

    <div class="flex justify-center">
      <button
        class="bg-blue-600 text-white px-6 py-3 rounded-lg shadow hover:bg-blue-700 transition"
      >
        Начать покупки
      </button>
    </div>
  </div>
</template>
